language: go

addons:
  hosts:
    - quic.clemente.io

go:
  - 1.x
  - 1.11.x
  - tip

env:
    - GO111MODULE=on

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  # Decrypts a script that installs an authenticated cookie
  # for git to use when cloning from googlesource.com.
  # Bypasses "bandwidth limit exceeded" errors.
  # See github.com/golang/go/issues/12933
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_3df18f9af81d_key -iv $encrypted_3df18f9af81d_iv -in dist/gitcookie.sh.enc -out dist/gitcookie.sh -d; fi
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash dist/gitcookie.sh; fi
  - go get -t ./...
  - go get golang.org/x/lint/golint
  - go get github.com/FiloSottile/vendorcheck
  - go get github.com/alecthomas/gometalinter

script:
  - golangci-lint run --disable-all -E golint -E gofmt -E misspell -E ineffassign -E goimports -E deadcode ./...
  - go test -mod=readonly -race ./...
  - go test -mod=vendor -race ./...

after_script:
  - golint ./...
